from __future__ import annotations


class ReasonCode:
    POLICY_DEFAULT_DENY = "POLICY.DEFAULT_DENY"
    POLICY_ALLOW_MATCHED = "POLICY.ALLOW_MATCHED"
    POLICY_DENY_MATCHED = "POLICY.DENY_MATCHED"
    POLICY_APPROVAL_REQUIRED = "POLICY.APPROVAL_REQUIRED"
    POLICY_TRANSFORM_APPLIED = "POLICY.TRANSFORM_APPLIED"

    DATA_PII_DETECTED = "DATA.PII_DETECTED"
    DATA_PHI_DETECTED = "DATA.PHI_DETECTED"
    DATA_SECRET_DETECTED = "DATA.SECRET_DETECTED"
    DATA_SENSITIVE_DETECTED = "DATA.SENSITIVE_DETECTED"

    RISK_LOW = "RISK.LOW"
    RISK_MEDIUM = "RISK.MEDIUM"
    RISK_HIGH = "RISK.HIGH"
    RISK_CRITICAL = "RISK.CRITICAL"
    RISK_TOOL_USE = "RISK.TOOL_USE"
    RISK_REGULATED_DOMAIN = "RISK.REGULATED_DOMAIN"
    RISK_HIGH_AUTONOMY = "RISK.HIGH_AUTONOMY"

    TOOL_ALLOWED = "TOOL.ALLOWED"
    TOOL_DENIED = "TOOL.DENIED"
    TOOL_APPROVAL_REQUIRED = "TOOL.APPROVAL_REQUIRED"
    TOOL_CONNECTOR_UNKNOWN = "TOOL.CONNECTOR_UNKNOWN"
    TOOL_ACTION_UNKNOWN = "TOOL.ACTION_UNKNOWN"
    TOOL_RATE_LIMIT_DECLARED = "TOOL.RATE_LIMIT_DECLARED"

    EVAL_POLICY_DECISION_MATCH = "EVAL.POLICY_DECISION_MATCH"
    EVAL_POLICY_DECISION_MISMATCH = "EVAL.POLICY_DECISION_MISMATCH"
    EVAL_SENSITIVE_DATA_LEAKAGE = "EVAL.SENSITIVE_DATA_LEAKAGE"
    EVAL_CITATION_MISSING = "EVAL.CITATION_MISSING"
    EVAL_TOOL_MISUSE = "EVAL.TOOL_MISUSE"

